name: AQI Full Pipeline

on:
  schedule:
    - cron: '0 * * * *'   # hourly
    - cron: '0 2 * * *'   # daily training 2 AM
  workflow_dispatch:

jobs:

  feature_pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt

      - name: Run Feature Pipeline
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
          OPENWEATHER_API_KEY: ${{ secrets.OPENWEATHER_API_KEY }}
          PROJECT_NAME: ${{ secrets.PROJECT_NAME }}
        run: python features/feature_pipeline.py


  preprocessing:
    needs: feature_pipeline
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt

      - name: Run Preprocessing Script
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
        run: python features/preprocessing.py


  model_training:
    if: github.event_name == 'schedule' && github.event.schedule == '0 2 * * *' || github.event_name == 'workflow_dispatch'
    needs: preprocessing
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt

      - name: Run Training Script
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
          DAGSHUB_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}
          DAGSHUB_REPO: ${{ secrets.DAGSHUB_REPO }}
        run: python training/train_model.py
